homework01
VadimFarutin/SPbAU-Software-Design pull request #1
Opened 2019-02-02 16:08 UTC by VadimFarutin

2019-02-28 17:58 UTC, ArtyomLobanov requested changes
Архитектура мне нравится. Единственное немного смущает, что утилитарный класс парсер имеет внутреннее состояние. Идеологически он должен знать про грамматику языка, а не про состояние интерпретатора. Я бы лучше передавал Environment в качестве аргумента метода parse. Но, наверное, это уже на грани придирки.
Из того, что ещё нужно поправить:
1. `echo build.gradle | cat` должно выводить `build.gradle`, а не содержимое файла с таким названием
2. `"ec"ho text` корректная команда
3. Следите за корректностью последовательности кавычек и пайпов
`echo "text`
`echo text |`
4.  Завершающаяся с ошибкой внешняя команда (например, `java -sfdgnhesghmj`) роняет интерпретатор
>Exception in thread "main" java.util.NoSuchElementException
        at java.base/java.util.Scanner.throwFor(Scanner.java:937)
        at java.base/java.util.Scanner.next(Scanner.java:1478)
        at ru.spbau.farutin.homework01.commands.ExternalCommand.execute(ExternalCommand.java:63)
        at ru.spbau.farutin.homework01.CLI.run(CLI.java:64)
        at ru.spbau.farutin.homework01.CLI.main(CLI.java:34)

2019-02-28 17:58 UTC, ArtyomLobanov commented on homework01/src/test/java/ru/spbau/farutin/homework01/commands/ExternalCommandTest.java
> +        arguments.add(argument);
[Collections.singletonList(argument)](https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#singletonList-T-)

2019-02-28 17:58 UTC, ArtyomLobanov commented on homework01/src/test/java/ru/spbau/farutin/homework01/CLITest.java
> +    public void testError() throws Exception {
Эти теста оба падают из-за различий в последовательностях переноса строки

> Expected: is "> exception\n> "
>      but: was "> exception\r\n> "

2019-02-28 17:58 UTC, ArtyomLobanov commented on homework01/src/test/java/ru/spbau/farutin/homework01/commands/ExternalCommandTest.java
> +    public void testExecuteExisting() throws Exception {
Тоже падает. При вашем подходе к запуску внешних команд, команды консоли (echo, dir) не доступны под windows.

2019-02-28 17:58 UTC, ArtyomLobanov commented on homework01/build.gradle
> +task run(type: JavaExec) {
Что-то как-то интерфейс у вас не дружелюбный
```
C:\practice\farutin\SPbAU-Software-Design\homework01>gradlew run
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
>
> textding 75% > :runecho text
>
> > echo $t75% > :runt=text
text
>
> Building 75% > :runecho some text
```
*жму enter*
```
C:\practice\farutin\SPbAU-Software-Design\homework01>gradlew run
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
>
> textding 75% > :runecho text
>
> > echo $t75% > :runt=text
text
>
> some text75% > :runecho some text
>
> Building 75% > :run
```

2019-02-28 17:58 UTC, ArtyomLobanov commented on homework01/src/main/java/ru/spbau/farutin/homework01/commands/CatCommand.java
> +        StringJoiner joiner = new StringJoiner("\n");
System.lineSeparator()

2019-02-28 17:58 UTC, ArtyomLobanov commented on homework01/src/main/java/ru/spbau/farutin/homework01/commands/EchoCommand.java
> +        String data = joiner.toString();
Можно через Stream API
```java
String data = arguments.stream()
    .map(Argument::getValue)
    .collect(Collectors.joining(" "));
```

2019-02-28 17:58 UTC, ArtyomLobanov commented on homework01/src/main/java/ru/spbau/farutin/homework01/commands/ExternalCommand.java
> +                process.waitFor();
Код возврата как-то нехорошо игнорировать. Да и поток ошибок прочитать хорошо бы.

2019-02-28 17:58 UTC, ArtyomLobanov commented on homework01/src/main/java/ru/spbau/farutin/homework01/commands/WcCommand.java
> +            int linesCnt = data.split("\n").length;
Теоретически, на каких-то платформах это может не сработать.

2019-02-28 17:58 UTC, ArtyomLobanov commented on homework01/src/main/java/ru/spbau/farutin/homework01/parser/ParserImpl.java
> +            if (c == ' ' || c == '$') {
Что насчёт " или '?
```
>echo "$t"
Unknown variable name t"
```

2019-02-28 17:58 UTC, ArtyomLobanov commented on homework01/src/main/java/ru/spbau/farutin/homework01/parser/ParserImpl.java
> +    private String readDoubleQuotesContent(Queue<Character> queue) {
Код почти полностью дублируется  с readSingleQuotesContent.

2019-02-28 17:58 UTC, ArtyomLobanov commented on homework01/src/main/java/ru/spbau/farutin/homework01/parser/ParserImpl.java
> +    private String readDoubleQuotesContent(Queue<Character> queue) {
Да и на readVariableName весьма похож. Попробуйте вынести из них общую логику.

2019-02-28 17:58 UTC, ArtyomLobanov commented on homework01/src/main/java/ru/spbau/farutin/homework01/parser/ParserImpl.java
> +    private String readDoubleQuotesContent(Queue<Character> queue) {
И на readName

2019-03-07 23:06 UTC, VadimFarutin commented on homework01/src/main/java/ru/spbau/farutin/homework01/commands/EchoCommand.java
> +        String data = joiner.toString();
```Argument::getValue``` кидает исключение, поэтому кажется его не получится использовать с ```map```

2019-03-08 10:10 UTC, ArtyomLobanov commented on homework01/src/main/java/ru/spbau/farutin/homework01/commands/EchoCommand.java
> +        String data = joiner.toString();
Да, действительно.

2019-03-08 10:23 UTC, ArtyomLobanov commented
1. testExecuteExisting всё ещё падает по выше описанным причинам
2. Если внешняя команда не существует или во время её выполнения происходит ошибка, то в консоль ничего не выводится. 
3. В bash кавычки экранируют друг друга.  Например, `echo " '  $x  ' "` выводит ` '  x_value ' `. Если вы считаете, что кавычки не должны друг друга экранировать, то и символы кавычек не надо выводить. У вас сейчас ни то ни сё 
```bash
> echo " '$x '"
 '$x '
```

2019-03-17 19:51 UTC, VadimFarutin commented
Вроде все исправил

2019-03-21 14:58 UTC, ArtyomLobanov commented
Ок. @yurii-litvinov

2019-03-24 17:09 UTC, yurii-litvinov approved these changes
Да, мне всё нравится, зачтена.

2019-03-24 17:09 UTC, yurii-litvinov commented on homework01/src/main/java/ru/spbau/farutin/homework01/CLI.java
> +        CLI cli = new CLI(System.in, System.out, System.out, parser);
Лучше перейти на Java посвежее и использовать varы повсюду, где тип надо писать дважды

2019-03-24 17:09 UTC, yurii-litvinov commented on homework01/src/main/java/ru/spbau/farutin/homework01/SessionStatus.java
> +    EXIT
По-хорошему, элементам перечисления тоже нужны комментарии

2019-03-24 17:09 UTC, yurii-litvinov commented on homework01/src/main/java/ru/spbau/farutin/homework01/commands/factory/CommandFactoryImpl.java
> +public class CommandFactoryImpl implements CommandFactory {
О, комментария не хватает

2019-06-19 22:24 UTC, merged