homework02
VadimFarutin/SPbAU-Software-Design pull request #2
Opened 2019-02-12 22:07 UTC by VadimFarutin

2019-03-14 17:53 UTC, ArtyomLobanov requested changes
Проверяйте корректность переданных параметров
```cmd
grep -A -10 pattern file
```

2019-03-14 17:53 UTC, ArtyomLobanov commented on homework01/src/main/java/ru/spbau/farutin/homework01/commands/GrepCommand.java
> +    private boolean containsWord(@NotNull String line, @NotNull Pattern pattern) {
У ключа -w смысл не в том, чтобы сматчить ровно одно слово, а в том, чтобы не сматчить какие-то крайние слова частично.
Должно быть так:
```cmd
>echo some text | grep "me text"
some text
>echo some text | grep -w "me text"
*ничего*
>echo so me text | grep -w "me text"
 so me text
```
Для обозначения границы слова в регэкспах есть \b.

2019-03-14 17:53 UTC, ArtyomLobanov commented on homework01/src/main/java/ru/spbau/farutin/homework01/commands/GrepCommand.java
> +            StringJoiner joiner = new StringJoiner("\n");
System.lineSeparator()

2019-03-21 15:12 UTC, ArtyomLobanov reviewed
Ок. @yurii-litvinov

2019-03-21 15:12 UTC, ArtyomLobanov commented on homework01/src/main/java/ru/spbau/farutin/homework01/commands/GrepCommand.java
> +    private boolean containsWord(@NotNull String line, @NotNull Pattern pattern) {
Этот метод уже можно удалить

2019-03-25 11:41 UTC, yurii-litvinov approved these changes
Мне всё нравится, зачтена

2019-06-19 22:25 UTC, merged